"""Cookie formatting utilities for yt-dlp compatibility."""

from __future__ import annotations


def _cookies_to_netscape(cookies_str: str) -> str:
    """Convert cookies string to Netscape HTTP Cookie File format for yt-dlp."""
    lines = [
        "# Netscape HTTP Cookie File",
        "# Generated by vkdownloader",
        "",
    ]
    if not cookies_str:
        return "\n".join(lines)

    for cookie in cookies_str.split("; "):
        if "=" in cookie:
            name, value = cookie.split("=", 1)
            lines.append(f".vkvideo.ru\tTRUE\t/\tFALSE\t0\t{name}\t{value}")
    return "\n".join(lines)


__all__ = ["_cookies_to_netscape"]
