"""Cookie formatting utilities for yt-dlp compatibility."""

from __future__ import annotations

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from playwright.async_api import Cookie


def _cookies_to_netscape(cookies_input: str | list[Cookie]) -> str:
    """Convert cookies to Netscape HTTP Cookie File format for yt-dlp.

    Accepts either a pre-formatted cookies string or a list of Cookie objects.
    When given Cookie objects, preserves the actual domain attribute.

    Args:
        cookies_input: Either a cookies string in format "name1=value1; name2=value2"
            or a list of Playwright Cookie objects.

    Returns:
        Netscape HTTP Cookie File format string.
    """
    lines = [
        "# Netscape HTTP Cookie File",
        "# Generated by vkdownloader",
        "",
    ]

    # Handle empty input
    if not cookies_input:
        return "\n".join(lines)

    # Handle Cookie objects list (dict-like TypedDict)
    if isinstance(cookies_input, list):
        for cookie_item in cookies_input:
            name = cookie_item["name"]
            value = cookie_item["value"]
            domain = cookie_item.get("domain", ".vkvideo.ru")
            path = cookie_item.get("path", "/")
            secure = "TRUE" if cookie_item.get("secure", False) else "FALSE"
            expires = int(cookie_item.get("expires", 0))

            if name and value:
                lines.append(f"{domain}\t{secure}\t{path}\tFALSE\t{expires}\t{name}\t{value}")
        return "\n".join(lines)

    # Handle string format (backward compatible)
    for cookie_part in cookies_input.split("; "):
        if "=" in cookie_part:
            name, value = cookie_part.split("=", 1)
            lines.append(f".vkvideo.ru\tTRUE\t/\tFALSE\t0\t{name}\t{value}")
    return "\n".join(lines)


__all__ = ["_cookies_to_netscape"]
