"""HLS downloader service with segment-level resume support."""

from __future__ import annotations

import asyncio
import json
import random
import signal
import ssl
from collections.abc import AsyncIterator, Callable
from dataclasses import dataclass
from pathlib import Path
from typing import TYPE_CHECKING
from urllib.parse import urljoin

import aiohttp
import yt_dlp
from structlog import get_logger

from ..config import Settings
from ..exceptions import ExtractionError
from ..models.dtos import HLSDownloadRequest
from ..models.enums import CookieSource, DownloadMethod
from ..models.video import Stream, VideoWithStreams
from ..services.extractor import VKVideoExtractor
from ..utils.security import validate_output_path
from ..utils.url_sanitizer import _strip_auth_params
from .downloader_throttle import RETRYABLE_STATUS_CODES, _retry_429_with_backoff, get_shutdown_event

if TYPE_CHECKING:
    from .downloader_throttle import URLBackoffCoordinator

logger = get_logger(__name__)

# Maximum retry attempts for getting new token on resume failure
MAX_RESUME_RETRIES = 3

# Track active ffmpeg processes for cleanup
_active_processes: set[asyncio.subprocess.Process] = set()


@dataclass
class FfmpegProgress:
    """Progress state from ffmpeg -progress pipe output."""

    frame: int | None = None
    fps: float | None = None
    speed: float | None = None
    total_size: int | None = None
    out_time_us: int | None = None
    out_time_ms: int | None = None
    out_time: str | None = None
    progress: str | None = None


class ProgressParser:
    """Parser for ffmpeg KEY=VALUE progress output."""

    @staticmethod
    def parse_line(line: str) -> tuple[str, str] | None:
        """Parse a single progress line in KEY=VALUE format.

        Args:
            line: Raw line from ffmpeg stderr.

        Returns:
            Tuple of (key, value) if valid format, None otherwise.
        """
        if "=" in line:
            key, value = line.strip().split("=", 1)
            return key, value
        return None


async def read_progress(
    stderr: asyncio.StreamReader,
    duration_ms: int | None = None,
    stderr_collector: list[bytes] | None = None,
) -> AsyncIterator[FfmpegProgress]:
    """Read ffmpeg progress output in real-time.

    Args:
        stderr: StreamReader from ffmpeg process stderr.
        duration_ms: Optional video duration in milliseconds for percentage calculation.
        stderr_collector: Optional list to collect raw stderr lines for error handling.

    Yields:
        FfmpegProgress objects as they are parsed.
    """
    progress = FfmpegProgress()
    while True:
        line = await stderr.readline()
        if not line:
            break
        if stderr_collector is not None:
            stderr_collector.append(line)
        parsed = ProgressParser.parse_line(line.decode())
        if parsed:
            key, value = parsed
            if key == "frame":
                progress.frame = int(value) if value != "N/A" else None
            elif key == "fps":
                progress.fps = float(value) if value != "N/A" else None
            elif key == "speed":
                # Parse "1.2x" -> 1.2
                progress.speed = float(value.rstrip("x")) if value != "N/A" else None
            elif key == "total_size":
                progress.total_size = int(value) if value != "N/A" else None
            elif key == "out_time_us":
                progress.out_time_us = int(value) if value != "N/A" else None
            elif key == "out_time_ms":
                progress.out_time_ms = int(value) if value != "N/A" else None
            elif key == "out_time":
                progress.out_time = value if value != "N/A" else None
            elif key == "progress":
                progress.progress = value
                yield progress
                if value == "end":
                    break
                progress = FfmpegProgress()  # Reset for next block


async def cancel_ffmpeg_process(
    process: asyncio.subprocess.Process,
    *,
    timeout: float = 5.0,
) -> bool:
    """Cancel and terminate an ffmpeg process gracefully.

    Args:
        process: The ffmpeg process to cancel.
        timeout: Seconds to wait for graceful termination before force kill.

    Returns:
        True if process was cancelled, False if process was already gone.
    """
    logger.info("cancelling_ffmpeg_process", pid=process.pid)
    try:
        process.terminate()
        try:
            await asyncio.wait_for(process.wait(), timeout=timeout)
            return True
        except TimeoutError:
            process.kill()
            await process.wait()
            return True
    except ProcessLookupError:
        return False


def _cookies_to_netscape(cookies_str: str) -> str:
    """Convert cookies string to Netscape HTTP Cookie File format for yt-dlp."""
    lines = [
        "# Netscape HTTP Cookie File",
        "# Generated by vkdownloader",
        "",
    ]
    if not cookies_str:
        return "\n".join(lines)

    for cookie in cookies_str.split("; "):
        if "=" in cookie:
            name, value = cookie.split("=", 1)
            lines.append(f".vkvideo.ru\tTRUE\t/\tFALSE\t0\t{name}\t{value}")
    return "\n".join(lines)


class HLSDownloader:
    """Downloads HLS streams to MP4 with segment-level resume support."""

    def __init__(self, settings: Settings | None = None) -> None:
        """
        Initialize HLSDownloader with optional settings.

        Args:
            settings: Application settings. Uses global settings if not provided.
        """
        self.settings = settings if settings is not None else Settings()

    def _build_ffmpeg_cmd(
        self, m3u8_url: str, output_file: Path, cookies: str | None = None
    ) -> list[str]:
        """Build ffmpeg command for HLS to MP4 conversion."""
        cookie_part = f"Cookie: {cookies}\r\n" if cookies else ""
        headers = f"User-Agent: {self.settings.user_agent}\r\nReferer: https://vkvideo.ru/\r\n{cookie_part}"

        cmd = [
            "ffmpeg",
            "-y",
            "-progress", "pipe:2",
            "-nostats",
            "-headers",
            headers,
            "-i",
            m3u8_url,
            "-c",
            "copy",
            str(output_file),
]

        return cmd

    async def download_with_ffmpeg(
        self,
        m3u8_url: str,
        output_file: Path,
        quality: str = "best",
        cookies: str | None = None,
        progress_callback: Callable[[FfmpegProgress], None] | None = None,
    ) -> Path | None:
        """Download HLS stream to MP4 using ffmpeg.

        Args:
            m3u8_url: HLS playlist URL.
            output_file: Output file path.
            quality: Quality string (e.g., "720", "1080").
            cookies: Optional cookies string for authenticated downloads.
            progress_callback: Optional callback for real-time progress updates.

        Returns:
            Path to output file on success, None on failure.
        """
        logger.info(
            "starting_ffmpeg_download",
            url=_strip_auth_params(m3u8_url),
            output=str(output_file),
            quality=quality,
            has_cookies=bool(cookies),
        )

        cmd = self._build_ffmpeg_cmd(m3u8_url, output_file, cookies)

        process = await asyncio.create_subprocess_exec(
            *cmd,
            stdout=asyncio.subprocess.PIPE,
            stderr=asyncio.subprocess.PIPE,
        )

        # Track process for cleanup on shutdown
        _active_processes.add(process)

        stderr_chunks: list[bytes] = []

        shutdown_event = get_shutdown_event()

        async def _monitor_progress() -> None:
            """Read progress and call callback, while collecting stderr for error handling."""
            assert process.stderr is not None
            async for progress in read_progress(process.stderr, stderr_collector=stderr_chunks):
                if shutdown_event.is_set():
                    await cancel_ffmpeg_process(process)
                    break
                if progress_callback:
                    progress_callback(progress)

        async def _drain_stderr() -> None:
            """Drain stderr to prevent buffer deadlock when no callback is provided."""
            assert process.stderr is not None
            while True:
                if shutdown_event.is_set():
                    await cancel_ffmpeg_process(process)
                    break
                line = await process.stderr.readline()
                if not line:
                    break
                stderr_chunks.append(line)

        try:
            # Run both process wait and stderr reading concurrently
            if progress_callback:
                process_task = asyncio.create_task(process.wait())
                monitor_task = asyncio.create_task(_monitor_progress())
                done, pending = await asyncio.wait(
                    [process_task, monitor_task],
                    return_when=asyncio.FIRST_COMPLETED,
                )
                # Cancel pending tasks
                for task in pending:
                    task.cancel()
                    try:
                        await task
                    except asyncio.CancelledError:
                        pass
            else:
                process_task = asyncio.create_task(process.wait())
                drain_task = asyncio.create_task(_drain_stderr())
                done, pending = await asyncio.wait(
                    [process_task, drain_task],
                    return_when=asyncio.FIRST_COMPLETED,
                )
                # Cancel pending tasks
                for task in pending:
                    task.cancel()
                    try:
                        await task
                    except asyncio.CancelledError:
                        pass

            stderr_data = (
                b"".join(stderr_chunks) if stderr_chunks else b""
            )

            if shutdown_event.is_set():
                await cancel_ffmpeg_process(process)
                return None

            if process.returncode != 0:
                error_msg = stderr_data.decode() if stderr_data else "Unknown ffmpeg error"
                logger.error("ffmpeg_download_failed", returncode=process.returncode, error=error_msg)
                return None

            logger.info("ffmpeg_download_completed", output=str(output_file))
            return output_file
        finally:
            _active_processes.discard(process)


async def download_hls_with_resume(
    request: HLSDownloadRequest,
    semaphore: asyncio.Semaphore | None = None,
) -> Path | None:
    """
    Download HLS stream with segment-level resume and token refresh.

    Downloads original HLS segments individually, tracks progress, and can resume
    after interruption by re-downloading missing segments. Uses batched merging
    to handle large number of segments.

    Args:
        request: HLSDownloadRequest containing all download parameters.
        semaphore: Optional shared semaphore for work-stealing concurrency in batch downloads.
            When None, creates a local semaphore based on settings.max_concurrent_downloads.

    Returns:
        Path to downloaded MP4 file on success, None on failure.
    """
    logger.info("starting_segment_download", url=_strip_auth_params(request.video_url), output=str(request.output_file), quality=request.quality)

    if request.settings is None:
        settings = Settings()
    else:
        settings = request.settings

    # Validate output path to prevent path traversal
    output_file = validate_output_path(request.output_file)

    segments_dir = output_file.parent / f".{output_file.stem}_segments"
    metadata_file = output_file.parent / f".{output_file.stem}_progress.json"

    segments_dir.mkdir(parents=True, exist_ok=True)
    shutdown_event = get_shutdown_event()

    try:
        downloaded_count = _load_downloaded_count(metadata_file)
        headers: dict[str, str] = {
            "User-Agent": settings.user_agent,
            "Referer": "https://vkvideo.ru/",
        }
        if request.cookies:
            headers["Cookie"] = request.cookies

        if settings.ssl_verify:
            connector = aiohttp.TCPConnector(limit=10)
        else:
            ssl_context = ssl.create_default_context()
            ssl_context.check_hostname = False
            ssl_context.verify_mode = ssl.CERT_NONE
            connector = aiohttp.TCPConnector(ssl=ssl_context, limit=10)
            logger.warning("ssl_verification_disabled", url=_strip_auth_params(request.video_url))

        async with aiohttp.ClientSession(connector=connector) as session:
            playlist_content = await _fetch_playlist_with_retry(
                session, request.video_url, request.m3u8_url, headers,
                request.extractor, settings
            )
            if not playlist_content:
                return None

            segments = _parse_m3u8_segments(playlist_content)
            logger.info("found_segments", count=len(segments), resume_from=downloaded_count)

            # Download missing segments concurrently
            # Use shared semaphore if provided, otherwise create local one based on settings
            semaphore_to_use = semaphore if semaphore is not None else asyncio.Semaphore(
                settings.max_concurrent_downloads
            )

            async def download_segment_concurrent(idx: int, segment_url: str) -> bool:
                """Download segment with semaphore rate limiting."""
                # Check for shutdown before starting - raise CancelledError to interrupt gather
                if shutdown_event.is_set():
                    raise asyncio.CancelledError("Download cancelled by user")
                async with semaphore_to_use:
                    # Check for shutdown after acquiring semaphore
                    if shutdown_event.is_set():
                        raise asyncio.CancelledError("Download cancelled by user")
                    full_url = segment_url
                    if not segment_url.startswith("http"):
                        full_url = urljoin(request.m3u8_url, segment_url)
                    segment_path = segments_dir / f"{idx:05d}.ts"
                    if not segment_path.exists():
                        result = await _download_segment(
                            session, full_url, segment_path, headers,
                            max_concurrent_downloads=settings.max_concurrent_downloads,
                            segment_index=idx,
                            backoff_coordinator=request.backoff_coordinator,
                            video_url=request.video_url,
                        )
                    else:
                        result = True
                # Anti-detection delay AFTER semaphore release (outside context block)
                # Delay only applies in sequential mode (max_concurrent_downloads == 1)
                # Skip when shared semaphore is provided (work-stealing context)
                if result and semaphore is None and settings.max_concurrent_downloads == 1:
                    # Check for shutdown in delay loop - raise to interrupt gather
                    if shutdown_event.is_set():
                        raise asyncio.CancelledError("Download cancelled by user")
                    delay = 1.5 + random.uniform(0, 0.5)
                    try:
                        # Allow interruption during delay
                        await asyncio.wait_for(shutdown_event.wait(), timeout=delay)
                        raise asyncio.CancelledError("Download cancelled by user")
                    except TimeoutError:
                        pass  # Normal completion
                return result

# Download all missing segments concurrently
            tasks = [
                asyncio.create_task(download_segment_concurrent(i, seg))
                for i, seg in enumerate(segments)
                if not (segments_dir / f"{i:05d}.ts").exists()
            ]
            if tasks:
                try:
                    # Wait for all tasks to complete, but allow shutdown interruption
                    results = await asyncio.gather(*tasks)
                except asyncio.CancelledError:
                    # Cancel any still-running tasks on interruption
                    for task in tasks:
                        if not task.done():
                            task.cancel()
                    # Wait for cancellation to propagate
                    await asyncio.gather(*tasks, return_exceptions=True)
                    logger.info("download_cancelled", reason="shutdown_requested")
                    return None
                downloaded_count = _load_downloaded_count(metadata_file) + sum(1 for r in results if r)
                _save_downloaded_count(metadata_file, downloaded_count)

                # Call progress callback for per-URL segment updates
                if request.progress_callback:
                    video_id = request.video_url.split("_")[-1] if "_" in request.video_url else request.video_url
                    request.progress_callback(video_id, downloaded_count, len(segments))

                # All downloaded - merge in batches
                if downloaded_count == len(segments):
                    logger.info("merging_segments", count=downloaded_count)
                    result = await _merge_segments_batched(segments_dir, output_file, len(segments))
                    if result:
                        _cleanup_segments(segments_dir, metadata_file)
                    return result

            return None
    finally:
        # Clean up on failure - only if segments_dir still exists
        # (cleanup is done inside try block on success, so dir won't exist then)
        if segments_dir.exists():
            _cleanup_segments(segments_dir, metadata_file)


async def _fetch_playlist_with_retry(
    session: aiohttp.ClientSession,
    video_url: str,
    m3u8_url: str,
    headers: dict[str, str],
    extractor: VKVideoExtractor | None,
    settings: Settings,
    max_retries: int = 3,
) -> str | None:
    """Fetch m3u8 playlist with token refresh on 403/410."""
    current_url = m3u8_url

    for attempt in range(max_retries):
        try:
            async with session.get(current_url, headers=headers) as response:
                if response.status == 200:
                    return await response.text()
                if response.status in (403, 410) and extractor:
                    logger.info("token_expired_fetching_new", attempt=attempt + 1)
                    # Check if cookie_source allows browser use for token refresh
                    if settings.cookie_source == CookieSource.BROWSER:
                        # Can refresh token via browser (recovery scenario)
                        streams, new_cookies = await extractor.extract_streams_with_cookies(
                            video_url, force_browser=True
                        )
                        if streams:
                            current_url = str(streams[0].url)
                            headers["Cookie"] = new_cookies or ""
                            continue
                    else:
                        # Cannot refresh without browser, log warning and return None
                        logger.warning(
                            "token_refresh_failed_cookie_source",
                            cookie_source=str(settings.cookie_source),
                            reason="Cannot refresh token without browser access",
                        )
                        return None
        except (aiohttp.ClientError, asyncio.CancelledError) as e:
            logger.warning("playlist_fetch_failed", error=str(e))

    return None


def _parse_m3u8_segments(content: str) -> list[str]:
    """Parse m3u8 playlist and extract segment URLs."""
    segments = []
    lines = content.split("\n")
    for line in lines:
        line = line.strip()
        if line and not line.startswith("#"):
            segments.append(line)
    return segments


async def _download_segment(
    session: aiohttp.ClientSession,
    segment_url: str,
    output_path: Path,
    headers: dict[str, str],
    max_concurrent_downloads: int = 1,
    segment_index: int = 0,
    backoff_coordinator: URLBackoffCoordinator | None = None,
    video_url: str | None = None,
) -> bool:
    """Download a single HLS segment.

    Args:
        session: aiohttp ClientSession for HTTP requests.
        segment_url: URL of the segment to download.
        output_path: Path to save the downloaded segment.
        headers: Request headers to use.
        max_concurrent_downloads: Maximum concurrent downloads. When 1, uses retry with backoff.
        segment_index: Index of the segment being downloaded (for logging).
        backoff_coordinator: Optional URLBackoffCoordinator for shared rate limiting.
        video_url: Original video URL for coordinator keying (required if coordinator provided).

    Returns:
        True on success, False on failure.
    """
    if max_concurrent_downloads == 1:
        content = await _retry_429_with_backoff(
            session, segment_url, headers, segment_index
        )
        if content is not None:
            with open(output_path, "wb") as f:
                f.write(content)
            return True
        return False

    # Existing logic for parallel mode with shared backoff support
    shutdown_event = get_shutdown_event()

    # Check for shared backoff before download attempt
    if backoff_coordinator and video_url:
        was_paused = await backoff_coordinator.wait_if_paused(video_url)
        if was_paused and shutdown_event.is_set():
            return False

    try:
        async with session.get(segment_url, headers=headers) as response:
            if response.status == 200:
                with open(output_path, "wb") as f:
                    f.write(await response.read())
                return True
            logger.warning("segment_download_failed", status=response.status)
            # Notify coordinator of rate limit for shared backoff
            if backoff_coordinator and video_url and response.status in RETRYABLE_STATUS_CODES:
                await backoff_coordinator.pause(video_url, 10.0)
            return False
    except aiohttp.ClientError as e:
        logger.error("segment_download_error", error=str(e))
        return False


def _build_ffmpeg_concat_command(file_list_path: Path, output_file: Path) -> list[str]:
    """Build ffmpeg concat command for merging files.

    Args:
        file_list_path: Path to the file list text file.
        output_file: Path to the output file.

    Returns:
        Command list for ffmpeg.
    """
    cmd = [
        "ffmpeg",
        "-y",
        "-f",
        "concat",
        "-safe",
        "0",
        "-i",
        str(file_list_path),
        "-c",
        "copy",
        str(output_file),
    ]

    return cmd


async def _merge_batch_segments(batch_files: list[Path], temp_dir: Path) -> Path | None:
    """Merge a batch of segments into a single temp file.

    Args:
        batch_files: List of segment file paths to merge.
        temp_dir: Directory for temp files.

    Returns:
        Path to merged batch file on success, None on failure.
    """
    # Derive batch_start from first file's index (e.g., "00000.ts" -> 0)
    batch_start = int(batch_files[0].stem)
    batch_output = temp_dir / f"batch_{batch_start:05d}.ts"
    file_list_path = temp_dir / f"batch_list_{batch_start}.txt"

    # Write file list for concat demuxer
    with open(file_list_path, "w", encoding="utf-8") as f:
        for segment_path in batch_files:
            f.write(f"file '{segment_path.as_posix()}'\n")

    cmd = _build_ffmpeg_concat_command(file_list_path, batch_output)

    process = await asyncio.create_subprocess_exec(
        *cmd,
        stdout=asyncio.subprocess.PIPE,
        stderr=asyncio.subprocess.PIPE,
    )

    stdout, stderr = await process.communicate()

    if process.returncode != 0:
        error = stderr.decode() if stderr else "Unknown error"
        logger.error("batch_merge_failed", error=error[:200])
        return None

    # Remove individual segment files after batch merge
    for segment_path in batch_files:
        segment_path.unlink()
    file_list_path.unlink()

    return batch_output


async def _perform_final_merge(temp_files: list[Path], output_file: Path) -> bool:
    """Merge all batch temp files into final output.

    Args:
        temp_files: List of batch temp file paths to merge.
        output_file: Final output file path.

    Returns:
        True on success, False on failure.
    """
    final_list_path = temp_files[0].parent / "final_list.txt"

    # Write file list for concat demuxer
    with open(final_list_path, "w", encoding="utf-8") as f:
        for temp_file in temp_files:
            f.write(f"file '{temp_file.as_posix()}'\n")

    cmd = _build_ffmpeg_concat_command(final_list_path, output_file)

    process = await asyncio.create_subprocess_exec(
        *cmd,
        stdout=asyncio.subprocess.PIPE,
        stderr=asyncio.subprocess.PIPE,
    )

    stdout, stderr = await process.communicate()

    if process.returncode == 0:
        logger.info("merge_completed", output=str(output_file))
        final_list_path.unlink()
        for tf in temp_files:
            tf.unlink()
        return True

    logger.error("final_merge_failed", error=stderr.decode()[:200] if stderr else "Unknown")
    return False


async def _merge_segments_batched(segments_dir: Path, output_file: Path, count: int) -> Path | None:
    """Merge segments in batches to avoid command line limits.

    Args:
        segments_dir: Directory containing segment files.
        output_file: Final output file path.
        count: Total number of segments to merge.

    Returns:
        Path to output file on success, None on failure.
    """
    batch_size = 100
    temp_files: list[Path] = []

    # Process in batches
    for batch_start in range(0, count, batch_size):
        batch_end = min(batch_start + batch_size, count)
        batch_files = [segments_dir / f"{i:05d}.ts" for i in range(batch_start, batch_end)]

        # Check all files exist
        if not all(f.exists() for f in batch_files):
            continue

        result = await _merge_batch_segments(batch_files, segments_dir)
        if result is None:
            return None

        temp_files.append(result)

    # Final merge of all batches
    if temp_files:
        if await _perform_final_merge(temp_files, output_file):
            return output_file

    return None


def _load_downloaded_count(metadata_file: Path) -> int:
    """Load downloaded segment count from metadata."""
    if metadata_file.exists():
        try:
            with open(metadata_file, encoding="utf-8") as f:
                data: dict[str, int] = json.load(f)
                return data.get("downloaded_count", 0)
        except (json.JSONDecodeError, OSError):
            return 0
    return 0


def _save_downloaded_count(metadata_file: Path, count: int) -> None:
    """Save downloaded segment count to metadata."""
    with open(metadata_file, "w", encoding="utf-8") as f:
        json.dump({"downloaded_count": count}, f)


def _cleanup_segments(segments_dir: Path, metadata_file: Path) -> None:
    """Clean up downloaded segments."""
    for f in segments_dir.glob("*"):
        f.unlink()
    try:
        segments_dir.rmdir()
    except OSError:
        pass
    metadata_file.unlink(missing_ok=True)


async def _cancel_all_downloads() -> None:
    """Cancel all active downloads and processes."""
    logger.info("cancelling_all_downloads", active_processes=len(_active_processes))

    # Cancel all tracked ffmpeg processes
    for process in list(_active_processes):
        try:
            process.terminate()
            try:
                await asyncio.wait_for(process.wait(), timeout=3.0)
            except TimeoutError:
                process.kill()
                await process.wait()
        except ProcessLookupError:
            pass
        except Exception as e:
            logger.warning("process_cancel_error", error=str(e))

    _active_processes.clear()


# Track if signal handlers already setup to prevent duplicate registration
_signal_handlers_setup = False


def setup_signal_handlers() -> None:
    """Setup signal handlers for graceful shutdown on SIGINT/SIGTERM."""
    global _signal_handlers_setup
    if _signal_handlers_setup:
        return

    shutdown_event = get_shutdown_event()

    def _handle_signal() -> None:
        """Signal handler to trigger graceful shutdown."""
        if not shutdown_event.is_set():
            logger.info("shutdown_signal_received")
            shutdown_event.set()

    try:
        loop = asyncio.get_running_loop()
    except RuntimeError:
        loop = None

    if loop is not None:
        for sig in (signal.SIGINT, signal.SIGTERM):
            try:
                loop.add_signal_handler(sig, _handle_signal)
                _signal_handlers_setup = True
            except NotImplementedError:
                # Windows doesn't support loop.add_signal_handler in some Python versions
                # Use signal.signal as fallback
                signal.signal(sig, lambda s, f: _handle_signal())
                _signal_handlers_setup = True
    else:
        # Fallback for non-async context
        for sig in (signal.SIGINT, signal.SIGTERM):
            signal.signal(sig, lambda s, f: _handle_signal())
            _signal_handlers_setup = True


async def download_with_ytdlp_with_resume_fallback(
    video_url: str,
    m3u8_url: str,
    output_file: Path,
    quality: str,
    extractor: VKVideoExtractor | None,
    settings: Settings | None = None,
    cookies: str | None = None,
) -> Path | None:
    """Download using yt-dlp with automatic segment-based resume on failure.

    Flow:
    1. Try yt-dlp download
    2. On failure with partial file: get fresh token via browser + switch to segment download
    3. Segment download resumes from last checkpoint

    Args:
        video_url: Original VK video URL.
        m3u8_url: HLS playlist URL (may be stale).
        output_file: Output file path.
        quality: Quality string.
        extractor: VKVideoExtractor for token refresh.
        settings: Application settings.
        cookies: Optional cookies string for authenticated downloads.

    Returns:
        Path to downloaded file on success, None on failure.
    """
    if settings is None:
        settings = Settings()

    retry_count = 0

    while retry_count <= MAX_RESUME_RETRIES:
        result = await _download_with_ytdlp(video_url, output_file, quality, settings, cookies)

        if result:
            if retry_count > 0:
                logger.info("download_completed_after_retries", retries=retry_count)
            return result

        retry_count += 1

        # Check for partial file - switch to segment download with fresh token
        validated_output = validate_output_path(output_file, warning=False)
        if validated_output.exists() and validated_output.stat().st_size > 0:
            logger.warning(
                "download_interrupted_switching_to_segments",
                path=str(validated_output),
                size=validated_output.stat().st_size,
                retry=retry_count,
            )

            # Get fresh m3u8 URL with new token via browser
            if retry_count <= MAX_RESUME_RETRIES:
                logger.info("attempting_segment_resume", retry=retry_count)

                try:
                    if extractor is None:
                        extractor = VKVideoExtractor(settings=settings)
                    # Force browser for token refresh during resume (recovery scenario)
                    browser_streams, cookies = await extractor.extract_streams_with_cookies(
                        video_url, force_browser=True
                    )
                    if browser_streams:
                        m3u8_url = str(browser_streams[0].url)
                        logger.info("fresh_token_obtained_for_resume")
                        # Remove partial file to start clean segment download
                        validated_output.unlink()
                        # Continue to segment download
                        segment_result = await download_hls_with_resume(
                            HLSDownloadRequest(
                                video_url=video_url,
                                m3u8_url=m3u8_url,
                                output_file=validated_output,
                                quality=quality,
                                cookies=cookies,
                                settings=settings,
                                extractor=extractor,
                            )
                        )
                        if segment_result:
                            return segment_result
                except (ExtractionError, OSError, ValueError) as e:
                    logger.warning("failed_to_refresh_token", error=str(e))
            else:
                logger.error("max_retries_exceeded")
                return None
        else:
            # No partial file and no success - original failure, no point in segment download
            return None

    # All retries exhausted without success
    return None


async def _download_with_ytdlp(
    video_url: str,
    output_file: Path,
    quality: str,
    settings: Settings,
    cookies: str | None = None,
) -> Path | None:
    """Download using yt-dlp."""
    logger.info("starting_ytdlp_download", url=_strip_auth_params(video_url), output=str(output_file), quality=quality)
    quality_str = quality.replace("p", "") if quality else "720"
    user_agent = settings.user_agent
    shutdown_event = get_shutdown_event()

    def _download() -> str:
        # Check shutdown before starting download
        if shutdown_event.is_set():
            raise RuntimeError("Download cancelled")

        if not settings.ssl_verify:
            logger.warning("ssl_verification_disabled", url=_strip_auth_params(video_url))

        ydl_opts = {
            "outtmpl": str(output_file),
            "quiet": False,
            "no_warnings": True,
            "format": f"best[height<={quality_str}]",
            "nocheckcertificate": not settings.ssl_verify,
            "hls_prefer_native": True,
            "concurrent_fragments": settings.max_concurrent_downloads,
            "throttledratelimit": settings.throttled_rate,
            "http_chunk_size": settings.http_chunk_size,
            "http_headers": {
                "User-Agent": user_agent,
                "Referer": "https://vkvideo.ru/",
            },
            "socket_timeout": 180,
            "retries": 10,
            "fragment_retries": 10,
        }

        # Add cookies file generation if cookies provided
        if cookies:
            cookie_file = output_file.parent / f".{output_file.stem}_cookies.txt"
            cookie_file.write_text(_cookies_to_netscape(cookies))
            ydl_opts["cookiefile"] = str(cookie_file)

        try:
            with yt_dlp.YoutubeDL(ydl_opts) as ydl:
                ydl.download([video_url])
            return str(output_file)
        except Exception as e:
            # Re-raise as DownloadError to distinguish from cancellation
            if "cancelled" in str(e).lower() or shutdown_event.is_set():
                raise RuntimeError("Download cancelled") from e
            raise

    loop = asyncio.get_running_loop()

    # Create task for the executor to allow cancellation
    download_task = asyncio.ensure_future(
        loop.run_in_executor(None, _download)
    )

    try:
        result = await download_task
        return Path(result)
    except asyncio.CancelledError:
        logger.info("yt_dlp_download_cancelled")
        # Cancel the executor task (though the thread will continue, it will be
        # cleaned up when the process exits or on subsequent runs)
        if not download_task.done():
            download_task.cancel()
        raise
    except Exception as e:
        logger.error("download_failed", error=str(e))
        return None


async def perform_download(
    url: str,
    quality: str,
    output_file: Path,
    method: DownloadMethod,
    extractor: VKVideoExtractor | None = None,
    settings: Settings | None = None,
    backoff_coordinator: URLBackoffCoordinator | None = None,
    semaphore: asyncio.Semaphore | None = None,
    progress_callback: Callable[[str, int, int], None] | None = None,
    video_data: VideoWithStreams | None = None,
    selected_stream: Stream | None = None,
) -> Path | None:
    """Perform video download using the specified method.

    Args:
        url: VK Video URL to download.
        quality: Quality string (e.g., "720", "1080").
        output_file: Output file path.
        method: Download method (yt-dlp, ffmpeg, or auto).
        extractor: Optional VKVideoExtractor for token refresh.
        settings: Application settings.
        backoff_coordinator: Optional shared URLBackoffCoordinator for rate limiting.
        semaphore: Optional shared semaphore for work-stealing concurrency in batch downloads.
        progress_callback: Optional callback for per-URL segment progress (video_id, downloaded, total).
        video_data: Optional pre-extracted video data with streams. When provided, skips extraction.
        selected_stream: Optional pre-selected stream. When provided, used instead of streams[0].

    Returns:
        Path to downloaded file on success, None on failure.
    """
    logger.info("starting_download", method=str(method), url=_strip_auth_params(url), quality=quality, output=str(output_file))

    if settings is None:
        settings = Settings()

    if extractor is None:
        extractor = VKVideoExtractor(settings=settings)

    # Use pre-extracted data when provided, otherwise extract streams
    if video_data is not None and selected_stream is not None:
        streams = video_data.streams
        m3u8_url = str(selected_stream.url)
    else:
        # Get m3u8 URL via yt-dlp (most reliable for extraction)
        video_data = await extractor.extract_streams(url)
        streams = video_data.streams

        if not streams:
            logger.error("no_streams_found", url=_strip_auth_params(url))
            return None

        m3u8_url = str(streams[0].url)

    match method:
        case DownloadMethod.YTDLP:
            # Conditionally get cookies based on cookie_source setting
            if settings.cookie_source == CookieSource.BROWSER:
                browser_streams, cookies = await extractor.extract_streams_with_cookies(url)
                if browser_streams:
                    m3u8_url = str(browser_streams[0].url)
            else:
                browser_streams = None
                cookies = None
            return await download_with_ytdlp_with_resume_fallback(
                url, m3u8_url, output_file, quality, extractor, settings,
                cookies=cookies
            )
        case DownloadMethod.FFMPEG:
            # Conditionally get cookies based on cookie_source setting
            if settings.cookie_source == CookieSource.BROWSER:
                browser_streams, cookies = await extractor.extract_streams_with_cookies(url)
                if browser_streams:
                    m3u8_url = str(browser_streams[0].url)
            else:
                browser_streams = None
                cookies = None
            downloader = HLSDownloader(settings=settings)
            result = await downloader.download_with_ffmpeg(
                m3u8_url, output_file, quality, cookies
            )
            if result is None:
                logger.info("ffmpeg_failed_fallback_to_segment_download")
                result = await download_hls_with_resume(
                    HLSDownloadRequest(
                        video_url=url,
                        m3u8_url=m3u8_url,
                        output_file=output_file,
                        quality=quality,
                        cookies=cookies,
                        settings=settings,
                        extractor=extractor,
                        backoff_coordinator=backoff_coordinator,
                        semaphore=semaphore,
                        progress_callback=progress_callback,
                    )
                )
            return result
        case DownloadMethod.AUTO:
            # Auto: try yt-dlp first (more reliable), segment download for resume
            return await download_with_ytdlp_with_resume_fallback(
                url, m3u8_url, output_file, quality, extractor, settings
            )
        case _:
            logger.error("unknown_download_method", method=str(method))
            return None
